### PR TITLE
The attribute standard_relationship should be a collection

### LINKED ISSUE #5: The attribute standard_relationship should be a collection
As titled

### PR DESCRIPTION
**Pull request by andrew2net**
fixes #5

### CODE REVIEW

**Comment by ronaldtse** [comment]
@andrew2net can you add the spec fixture for the failure so we don't encounter it again? You can just copy that file from rawbib. Thanks.

**Comment by andrew2net** [comment]
@ronaldtse I can add fixtures. But we need to create another test for this cases because lutaml-model creates collection automatically even there is no `collection: true` option. So round-trip test doesn't fall without the option. But using `Ieee::Idams::Publication`'s data is tricky because we need to handle 3 value types. For example without `collection: true` option abstract's value can be:
- `nil` if there is no any abstracts
- `ArticleAbstract` instance when there is only one abstract
- `[ArticleAbstract]` array of abstract instances if there are more than one abstract

With the option we always get an array and can handle it same and simplify code in the relaton-ieee.
I seems there are other attributes what need to be collection. I'll create new tests as soon as I find all of them.

**Comment by ronaldtse** [comment]
@andrew2net I think this is a problem in lutaml-model for being implicit or "not caring" the actual model.

This just means that `ArticleAbstract` is clearly a collection because it could be `0`, `1` and `*`, i.e. `[0..*]`.

I think when `collection: true` is not given, then we must enforce there is 1 and only 1 instance. Ping @HassanAkbar .

**Comment by andrew2net** [comment]
> I think this is a problem in lutaml-model for being implicit or "not caring" the actual model.

@ronaldtse agree. If lutaml-model caries the actual model then the round-test will fall without collection option when an attribute is actually collection. So we won't need addition tests in this gem.

**Comment by ronaldtse** [comment]
Agree with @andrew2net , I've posted the issue at:
* https://github.com/lutaml/lutaml-model/issues/185

**Review by ronaldtse — APPROVED** [review]
@andrew2net thank you, please feel free to merge!

**Pull request merged**
